version: '3.8'

services:
  bot:
    build: .
    container_name: email_notifier_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./o365_token.txt:/app/o365_token.txt
      - ./weekly_report.json:/app/weekly_report.json
      - ./weekly_report_me.json:/app/weekly_report_me.json
      - ./bot_checkpoint.json:/app/bot_checkpoint.json
      - ./bot_log.txt:/app/bot_log.txt

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
